import { useNavigate } from 'react-router-dom';
import CardPrimary from '../../../common/card/CardPrimary';
import TablePrimary from '../../../common/table/TablePrimary';
import TopicOfPage from '../../../common/topic/TopicOfPage';

const mockupDatas = [
    {
        _id: '01',
        no: 1,
        product_id: '60367919',
        product_name: 'ตู้อเนกประสงค์ Ocean OCF-10170 100x53x120 ซม. สีขาว',
        product_unit: 'ใบ',
        product_weight: 25.5,
        product_category: 'ตู้เก็บของอเนกประสงค์',
        product_sub_category: 'ตู้เก็บของพลาสติก',
        store_group: 'กลุ่มที่ 1',
        product_price: '2,500.00',
        available_production_lines: 'Line-1, Line-2',
    },
    {
        _id: '02',
        no: 2,
        product_id: '60367919',
        product_name: 'ตู้อเนกประสงค์ Ocean OCF-10170 100x53x120 ซม. สีขาว',
        product_unit: 'ใบ',
        product_weight: 25.5,
        product_category: 'ตู้เก็บของอเนกประสงค์',
        product_sub_category: 'ตู้เก็บของพลาสติก',
        store_group: 'กลุ่มที่ 2',
        product_price: '2,200.00',
        available_production_lines: 'Line-1, Line-2',
    },
    {
        _id: '03',
        no: 3,
        product_id: '60367919',
        product_name: 'ตู้อเนกประสงค์ Ocean OCF-10170 100x53x120 ซม. สีขาว',
        product_unit: 'ใบ',
        product_weight: 25.5,
        product_category: 'ตู้เก็บของอเนกประสงค์',
        product_sub_category: 'ตู้เก็บของพลาสติก',
        store_group: 'กลุ่มที่ 3',
        product_price: '2,350.00',
        available_production_lines: 'Line-1, Line-2',
    },
    {
        _id: '04',
        no: 4,
        product_id: '60367919',
        product_name: 'ตู้อเนกประสงค์ Ocean OCF-10170 100x53x120 ซม. สีขาว',
        product_unit: 'ใบ',
        product_weight: 25.5,
        product_category: 'ตู้เก็บของอเนกประสงค์',
        product_sub_category: 'ตู้เก็บของพลาสติก',
        store_group: 'กลุ่มที่ 4',
        product_price: '2,100.00',
        available_production_lines: 'Line-1, Line-2',
    },
    {
        _id: '05',
        no: 5,
        product_id: '60367926',
        product_name: 'ตู้กับข้าว 2/4 Zagio CR2040-S 61.5x43x120.5 ซม. สีเงิน',
        product_unit: 'ใบ',
        product_weight: 18.2,
        product_category: 'ตู้กับข้าว',
        product_sub_category: 'ตู้กับข้าวแบบมีลิ้นชัก',
        store_group: 'กลุ่มที่ 1',
        product_price: '3,200.00',
        available_production_lines: 'Line-2, Line-3',
    },
    {
        _id: '06',
        no: 6,
        product_id: '60367926',
        product_name: 'ตู้กับข้าว 2/4 Zagio CR2040-S 61.5x43x120.5 ซม. สีเงิน',
        product_unit: 'ใบ',
        product_weight: 18.2,
        product_category: 'ตู้กับข้าว',
        product_sub_category: 'ตู้กับข้าวแบบมีลิ้นชัก',
        store_group: 'กลุ่มที่ 2',
        product_price: '2,950.00',
        available_production_lines: 'Line-2, Line-3',
    },
    {
        _id: '07',
        no: 7,
        product_id: '60367926',
        product_name: 'ตู้กับข้าว 2/4 Zagio CR2040-S 61.5x43x120.5 ซม. สีเงิน',
        product_unit: 'ใบ',
        product_weight: 18.2,
        product_category: 'ตู้กับข้าว',
        product_sub_category: 'ตู้กับข้าวแบบมีลิ้นชัก',
        store_group: 'กลุ่มที่ 3',
        product_price: '3,100.00',
        available_production_lines: 'Line-2, Line-3',
    },
    {
        _id: '08',
        no: 8,
        product_id: '60367926',
        product_name: 'ตู้กับข้าว 2/4 Zagio CR2040-S 61.5x43x120.5 ซม. สีเงิน',
        product_unit: 'ใบ',
        product_weight: 18.2,
        product_category: 'ตู้กับข้าว',
        product_sub_category: 'ตู้กับข้าวแบบมีลิ้นชัก',
        store_group: 'กลุ่มที่ 4',
        product_price: '2,850.00',
        available_production_lines: 'Line-2, Line-3',
    },
    {
        _id: '09',
        no: 9,
        product_id: '60367932',
        product_name: 'ตู้วางเตาแก็ส Zagio CR120-S 122x45.5x85.5 ซม. สีเงิน',
        product_unit: 'ใบ',
        product_weight: 22.8,
        product_category: 'ตู้วางเตาแก็ส',
        product_sub_category: 'ตู้วางเตาแก็สแบบมีล้อ',
        store_group: 'กลุ่มที่ 1',
        product_price: '2,800.00',
        available_production_lines: 'Line-1, Line-2, Line-3',
    },
    {
        _id: '10',
        no: 10,
        product_id: '60367932',
        product_name: 'ตู้วางเตาแก็ส Zagio CR120-S 122x45.5x85.5 ซม. สีเงิน',
        product_unit: 'ใบ',
        product_weight: 22.8,
        product_category: 'ตู้วางเตาแก็ส',
        product_sub_category: 'ตู้วางเตาแก็สแบบมีล้อ',
        store_group: 'กลุ่มที่ 2',
        product_price: '2,600.00',
        available_production_lines: 'Line-1, Line-2, Line-3',
    },
    {
        _id: '11',
        no: 11,
        product_id: '60367932',
        product_name: 'ตู้วางเตาแก็ส Zagio CR120-S 122x45.5x85.5 ซม. สีเงิน',
        product_unit: 'ใบ',
        product_weight: 22.8,
        product_category: 'ตู้วางเตาแก็ส',
        product_sub_category: 'ตู้วางเตาแก็สแบบมีล้อ',
        store_group: 'กลุ่มที่ 3',
        product_price: '2,750.00',
        available_production_lines: 'Line-1, Line-2, Line-3',
    },
    {
        _id: '12',
        no: 12,
        product_id: '60367932',
        product_name: 'ตู้วางเตาแก็ส Zagio CR120-S 122x45.5x85.5 ซม. สีเงิน',
        product_unit: 'ใบ',
        product_weight: 22.8,
        product_category: 'ตู้วางเตาแก็ส',
        product_sub_category: 'ตู้วางเตาแก็สแบบมีล้อ',
        store_group: 'กลุ่มที่ 4',
        product_price: '2,550.00',
        available_production_lines: 'Line-1, Line-2, Line-3',
    },
    {
        _id: '13',
        no: 13,
        product_id: '60367945',
        product_name: 'ตู้เสื้อผ้า 2 บาน พร้อมราวแขวน สีขาว',
        product_unit: 'ใบ',
        product_weight: 35.0,
        product_category: 'ตู้เสื้อผ้า',
        product_sub_category: 'ตู้เสื้อผ้าแบบมีราวแขวน',
        store_group: 'กลุ่มที่ 1',
        product_price: '4,500.00',
        available_production_lines: 'Line-1',
    },
    {
        _id: '14',
        no: 14,
        product_id: '60367945',
        product_name: 'ตู้เสื้อผ้า 2 บาน พร้อมราวแขวน สีขาว',
        product_unit: 'ใบ',
        product_weight: 35.0,
        product_category: 'ตู้เสื้อผ้า',
        product_sub_category: 'ตู้เสื้อผ้าแบบมีราวแขวน',
        store_group: 'กลุ่มที่ 2',
        product_price: '4,200.00',
        available_production_lines: 'Line-1',
    },
    {
        _id: '15',
        no: 15,
        product_id: '60367945',
        product_name: 'ตู้เสื้อผ้า 2 บาน พร้อมราวแขวน สีขาว',
        product_unit: 'ใบ',
        product_weight: 35.0,
        product_category: 'ตู้เสื้อผ้า',
        product_sub_category: 'ตู้เสื้อผ้าแบบมีราวแขวน',
        store_group: 'กลุ่มที่ 3',
        product_price: '4,350.00',
        available_production_lines: 'Line-1',
    },
    {
        _id: '16',
        no: 16,
        product_id: '60367945',
        product_name: 'ตู้เสื้อผ้า 2 บาน พร้อมราวแขวน สีขาว',
        product_unit: 'ใบ',
        product_weight: 35.0,
        product_category: 'ตู้เสื้อผ้า',
        product_sub_category: 'ตู้เสื้อผ้าแบบมีราวแขวน',
        store_group: 'กลุ่มที่ 4',
        product_price: '4,100.00',
        available_production_lines: 'Line-1',
    },
    {
        _id: '17',
        no: 17,
        product_id: '60367958',
        product_name: 'ตู้เก็บเครื่องมือ พร้อมล้อ 5 ชั้น สีแดง',
        product_unit: 'ใบ',
        product_weight: 28.5,
        product_category: 'ตู้เก็บเครื่องมือ',
        product_sub_category: 'ตู้เก็บเครื่องมือแบบมีล้อ',
        store_group: 'กลุ่มที่ 1',
        product_price: '3,800.00',
        available_production_lines: 'Line-2',
    },
    {
        _id: '18',
        no: 18,
        product_id: '60367958',
        product_name: 'ตู้เก็บเครื่องมือ พร้อมล้อ 5 ชั้น สีแดง',
        product_unit: 'ใบ',
        product_weight: 28.5,
        product_category: 'ตู้เก็บเครื่องมือ',
        product_sub_category: 'ตู้เก็บเครื่องมือแบบมีล้อ',
        store_group: 'กลุ่มที่ 2',
        product_price: '3,550.00',
        available_production_lines: 'Line-2',
    },
    {
        _id: '19',
        no: 19,
        product_id: '60367958',
        product_name: 'ตู้เก็บเครื่องมือ พร้อมล้อ 5 ชั้น สีแดง',
        product_unit: 'ใบ',
        product_weight: 28.5,
        product_category: 'ตู้เก็บเครื่องมือ',
        product_sub_category: 'ตู้เก็บเครื่องมือแบบมีล้อ',
        store_group: 'กลุ่มที่ 3',
        product_price: '3,700.00',
        available_production_lines: 'Line-2',
    },
    {
        _id: '20',
        no: 20,
        product_id: '60367958',
        product_name: 'ตู้เก็บเครื่องมือ พร้อมล้อ 5 ชั้น สีแดง',
        product_unit: 'ใบ',
        product_weight: 28.5,
        product_category: 'ตู้เก็บเครื่องมือ',
        product_sub_category: 'ตู้เก็บเครื่องมือแบบมีล้อ',
        store_group: 'กลุ่มที่ 4',
        product_price: '3,450.00',
        available_production_lines: 'Line-2',
    },
];

export default function ProductList() {

    const navigate = useNavigate();

    return (
        <>
            <TopicOfPage text='รายการสินค้าทั้งหมด' />
            <CardPrimary>
                <TablePrimary
                    data={mockupDatas}
                    rowsPerPage={30}
                    tHeadDatas={[
                        { tHeadTiltle: 'No.', cssTextAlign: 'center', key: 'no' },
                        { tHeadTiltle: 'รหัสสินค้า', cssTextAlign: 'left', key: 'product_id' },
                        { tHeadTiltle: 'ชื่อสินค้า', cssTextAlign: 'left', key: 'product_name' },
                        { tHeadTiltle: 'หน่วยเรียก', cssTextAlign: 'left', key: 'product_unit' },
                        { tHeadTiltle: 'น้ำหนักสินค้า [kg]', cssTextAlign: 'left', key: 'product_weight' },
                        { tHeadTiltle: 'ประเภทสินค้า', cssTextAlign: 'left', key: 'product_category' },
                        { tHeadTiltle: 'ประเภทสินค้าย่อย', cssTextAlign: 'left', key: 'product_sub_category' },
                        { tHeadTiltle: 'Line ที่ผลิตได้', cssTextAlign: 'left', key: 'available_production_lines' },
                        { tHeadTiltle: 'กลุ่มร้านค้า', cssTextAlign: 'left', key: 'store_group' },
                        { tHeadTiltle: 'ราคาสินค้า / หน่วย [บาท]', cssTextAlign: 'right', key: 'product_price' },
                        { tHeadTiltle: 'Action', cssTextAlign: 'center' },
                    ]}
                    keyNameOfId='_id'
                    editOnClick={id => navigate(`/edit-product?id=${id}`)}
                    deleteOnClick={id => console.log('delete', id as string)}
                />
            </CardPrimary>
        </>
    )
}
